# Ficheiro de teste do nosso novo ndppd-rs!

proxy eth0 {
    router yes
    timeout 500
    ttl 30000

    rule 2001:db8::1 {
        static
    }

    rule 1234:5678::/96 {
        iface eth1
    }
}