[general]
persistence_file=leases.json

[br1]
type=server
ipv4_range_start=10.0.0.2
ipv6_prefix=2804:14d:7e89:41a0:1234::
ipv6_prefix_len=80

[br2]
type=server
ipv4_range_start=10.0.1.2
ipv6_prefix=2804:14d:7e89:41a0:5678::
ipv6_prefix_len=80

[br0]
type=ndp-proxy
ipv6_prefix=2804:14d:7e89:41a0::
ipv6_prefix_len=64